import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Generates a professional Bank Report PDF for the farmer.
 * @param {Object} data - The data to include in the report.
 */
export const generateBankPDF = (data) => {
  const { 
    farmerName, 
    cropType, 
    landArea, 
    season, 
    location, 
    estimatedRevenue, 
    estimatedCost, 
    netProfit, 
    riskLevel, 
    date 
  } = data;
  
  const doc = new jsPDF();
  const primaryColor = [22, 163, 74]; // #16a34a

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Fasal Saathi - Agricultural Bank Report", 20, 25);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on: ${date}`, 160, 25);

  // Farmer Information Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Farmer Profile", 20, 55);
  doc.setLineWidth(0.5);
  doc.line(20, 57, 190, 57);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const profileInfo = [
    ["Farmer Name:", farmerName],
    ["Primary Crop:", cropType],
    ["Land Area:", `${landArea} acres`],
    ["Season:", season],
    ["Location:", location],
    ["Report Date:", date]
  ];

  autoTable(doc, {
    startY: 62,
    body: profileInfo,
    theme: "striped",
    styles: { fontSize: 10, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: "bold", width: 40 } }
  });

  // Financial Summary Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Financial Summary", 20, doc.lastAutoTable.finalY + 15);
  doc.line(20, doc.lastAutoTable.finalY + 17, 190, doc.lastAutoTable.finalY + 17);

  const financialTable = [
    ["Estimated Revenue", `INR ${estimatedRevenue.toLocaleString()}`],
    ["Estimated Cost", `INR ${estimatedCost.toLocaleString()}`],
    ["Net Profit", `INR ${netProfit.toLocaleString()}`],
    ["Risk Level", riskLevel]
  ];

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 22,
    body: financialTable,
    theme: "grid",
    head: [["Metric", "Amount (INR)"]],
    headStyles: { fillColor: primaryColor },
    styles: { fontSize: 11, cellPadding: 5 },
    columnStyles: { 0: { fontStyle: "normal" }, 1: { halign: "right" } }
  });

  // Footer Disclaimer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(0, 0, 0); // Black for visibility
  doc.text("This report is generated by Fasal Saathi AI Advisor based on historical data and AI predictions.", 20, pageHeight - 20);
  doc.text("It is intended for informational purposes and loan eligibility assessment.", 20, pageHeight - 15);

  doc.save(`FasalSaathi_BankReport_${farmerName.replace(/\s+/g, '_')}_${date.replace(/\//g, '_')}.pdf`);
};

/**
 * Generates a CSV file from the provided data.
 */
export const generateCSV = (data) => {
  const { 
    farmerName, 
    cropType, 
    landArea, 
    season, 
    location, 
    estimatedRevenue, 
    estimatedCost, 
    netProfit, 
    riskLevel, 
    date 
  } = data;
  
  const rows = [
    ["Category", "Value"],
    ["Farmer Name", farmerName],
    ["Primary Crop", cropType],
    ["Land Area (Acres)", landArea],
    ["Season", season],
    ["Location", location],
    ["Estimated Revenue (INR)", estimatedRevenue],
    ["Estimated Cost (INR)", estimatedCost],
    ["Net Profit (INR)", netProfit],
    ["Risk Level", riskLevel],
    ["Report Date", date]
  ];

  let csvContent = "data:text/csv;charset=utf-8," 
    + rows.map(e => e.join(",")).join("\n");

  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", `FasalSaathi_FinancialReport_${farmerName.replace(/\s+/g, '_')}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
